export enum TANMethodArgument {
    ALLOWED_FORMAT = "allowed_format",
    CANCEL_ALLOWED = "cancel_allowed",
    CHALLENGE_CLASS_REQUIRED = "challenge_class_required",
    CHALLENGE_VALUE_REQUIRED = "challenge_value_required",
    CHALLENGE_STRUCTURED = "challenge_structured",
    DESCRIPTION_REQUIRED = "description_required",
    HHD_UC_REQUIRED = "hhd_uc_required",
    INITIALIZATION_MODE = "initialization_mode",
    MAX_LENGTH_INPUT = "max_length_input",
    MAX_LENGTH_RETURNVALUE = "max_length_returnvalue",
    MULTIPLE_TANS_ALLOWED = "multiple_tans_allowed",
    NAME = "name",
    NUMBER_OF_SUPPORTED_LISTS = "number_of_supported_lists",
    PRINCIPAL_ACCOUNT_REQUIRED = "principal_account_required",
    SECURITY_FUNCTION = "security_feature",
    SMS_CHARGE_ACCOUNT_REQUIRED = "sms_charge_account_required",
    SUPPORTED_MEDIA_NUMBER = "supported_media_number",
    TAN_LIST_NUMBER_REQUIRED = "tan_list_number_required",
    TAN_PROCESS = "tan_process",
    TAN_TIME_DELAYED_ALLOWED = "tan_time_delayed_allowed",
    TAN_TIME_DIALOG_ASSOCIATION = "tan_time_dialog_association",
    TECH_ID = "tech_id",
    TEXT_RETURNVALUE = "text_returnvalue",
    ZKA_ID = "zka_id",
    ZKA_VERSION = "zka_version",
}
